// ─── SURAH NAME MAP (French + Arabic + English for voice recognition) ─────────
export const SURAH_NAMES = {
  "fatiha":1,"al-fatiha":1,"fatihah":1,"ouverture":1,
  "baqara":2,"al-baqara":2,"vache":2,"bakara":2,
  "imran":3,"al-imran":3,"famille d'imran":3,
  "nisa":4,"an-nisa":4,"femmes":4,
  "maida":5,"al-maida":5,"table":5,
  "anam":6,"al-anam":6,"troupeaux":6,
  "araf":7,"al-araf":7,"murailles":7,
  "anfal":8,"al-anfal":8,"dépouilles":8,
  "tawba":9,"at-tawba":9,"repentir":9,
  "yunus":10,"younes":10,"jonas":10,
  "hud":11,"houd":11,
  "yusuf":12,"youssef":12,"joseph":12,
  "rad":13,"ar-rad":13,"tonnerre":13,
  "ibrahim":14,"abraham":14,
  "hijr":15,"al-hijr":15,
  "nahl":16,"an-nahl":16,"abeilles":16,
  "isra":17,"al-isra":17,"voyage nocturne":17,
  "kahf":18,"al-kahf":18,"caverne":18,
  "maryam":19,"marie":19,
  "taha":20,"ta-ha":20,
  "anbiya":21,"al-anbiya":21,"prophètes":21,
  "hajj":22,"pèlerinage":22,
  "muminun":23,"croyants":23,
  "nur":24,"an-nur":24,"lumière":24,
  "furqan":25,"al-furqan":25,"critère":25,
  "shuara":26,"poètes":26,
  "naml":27,"an-naml":27,"fourmis":27,
  "qasas":28,"al-qasas":28,"récits":28,
  "ankabut":29,"araignée":29,
  "rum":30,"ar-rum":30,"romains":30,
  "luqman":31,"lokman":31,
  "sajda":32,"as-sajda":32,"prosternation":32,
  "ahzab":33,"al-ahzab":33,"coalisés":33,
  "saba":34,"saba'":34,
  "fatir":35,"créateur":35,
  "yasin":36,"ya-sin":36,
  "saffat":37,"as-saffat":37,"rangés":37,
  "sad":38,
  "zumar":39,"az-zumar":39,"groupes":39,
  "ghafir":40,"al-ghafir":40,"pardonneur":40,
  "fussilat":41,"explicitement":41,
  "shura":42,"ash-shura":42,"concertation":42,
  "zukhruf":43,"az-zukhruf":43,"ornements":43,
  "dukhan":44,"ad-dukhan":44,"fumée":44,
  "jathiya":45,"al-jathiya":45,"agenouillée":45,
  "ahqaf":46,"al-ahqaf":46,
  "muhammad":47,"combat":47,
  "fath":48,"al-fath":48,"victoire":48,
  "hujurat":49,"al-hujurat":49,"appartements":49,
  "qaf":50,
  "dhariyat":51,"adh-dhariyat":51,"vents":51,
  "tur":52,"at-tur":52,"mont":52,
  "najm":53,"an-najm":53,"étoile":53,
  "qamar":54,"al-qamar":54,"lune":54,
  "rahman":55,"ar-rahman":55,"miséricordieux":55,
  "waqia":56,"al-waqia":56,"événement":56,
  "hadid":57,"al-hadid":57,"fer":57,
  "mujadila":58,"al-mujadila":58,"discussion":58,
  "hashr":59,"al-hashr":59,"rassemblement":59,
  "mumtahana":60,"al-mumtahana":60,"éprouvée":60,
  "saff":61,"as-saff":61,"rang":61,
  "juma":62,"al-juma":62,"vendredi":62,
  "munafiqun":63,"hypocrites":63,
  "taghabun":64,"at-taghabun":64,"tromperie":64,
  "talaq":65,"at-talaq":65,"divorce":65,
  "tahrim":66,"at-tahrim":66,"interdiction":66,
  "mulk":67,"al-mulk":67,"royauté":67,
  "qalam":68,"al-qalam":68,"plume":68,
  "haqqa":69,"al-haqqa":69,"inévitable":69,
  "maarij":70,"al-maarij":70,"degrés":70,
  "nuh":71,"noé":71,
  "jinn":72,"al-jinn":72,"djinns":72,
  "muzzammil":73,"al-muzzammil":73,"enveloppé":73,
  "muddaththir":74,"al-muddaththir":74,"revêtu":74,
  "qiyama":75,"al-qiyama":75,"résurrection":75,
  "insan":76,"al-insan":76,"homme":76,
  "mursalat":77,"al-mursalat":77,"envoyés":77,
  "naba":78,"an-naba":78,"nouvelle":78,
  "naziat":79,"an-naziat":79,"arracheurs":79,
  "abasa":80,"froncement":80,
  "takwir":81,"at-takwir":81,"obscurcissement":81,
  "infitar":82,"al-infitar":82,"fissure":82,
  "mutaffifin":83,"fraudeurs":83,
  "inshiqaq":84,"al-inshiqaq":84,"déchirement":84,
  "buruj":85,"al-buruj":85,"constellations":85,
  "tariq":86,"at-tariq":86,"nocturne":86,
  "ala":87,"al-ala":87,"très-haut":87,
  "ghashiya":88,"al-ghashiya":88,"enveloppante":88,
  "fajr":89,"al-fajr":89,"aube":89,
  "balad":90,"al-balad":90,"cité":90,
  "shams":91,"ash-shams":91,"soleil":91,
  "layl":92,"al-layl":92,"nuit":92,
  "duha":93,"ad-duha":93,"matinée":93,
  "sharh":94,"inshirah":94,"ouverture de cœur":94,
  "tin":95,"at-tin":95,"figuier":95,
  "alaq":96,"al-alaq":96,"adhérence":96,
  "qadr":97,"al-qadr":97,"destin":97,
  "bayyina":98,"al-bayyina":98,"preuve":98,
  "zalzala":99,"az-zalzala":99,"séisme":99,
  "adiyat":100,"al-adiyat":100,"coursiers":100,
  "qaria":101,"al-qaria":101,"fracas":101,
  "takathur":102,"at-takathur":102,"accumulation":102,
  "asr":103,"al-asr":103,"après-midi":103,
  "humaza":104,"al-humaza":104,"calomniateur":104,
  "fil":105,"al-fil":105,"éléphant":105,
  "quraysh":106,"coréishites":106,
  "maun":107,"al-maun":107,"ustensiles":107,
  "kawthar":108,"al-kawthar":108,"abondance":108,
  "kafirun":109,"al-kafirun":109,"infidèles":109,
  "nasr":110,"an-nasr":110,"secours":110,
  "masad":111,"al-masad":111,"fibre":111,
  "ikhlas":112,"al-ikhlas":112,"sincérité":112,
  "falaq":113,"al-falaq":113,"aube naissante":113,
  "nas":114,"an-nas":114,"humanité":114,
};

export const RECITATORS = [
  { id: 'ar.alafasy',            label: 'Mishary Al-Afasy',            flag: '🇰🇼' },
  { id: 'ar.abdulbasitmurattal', label: 'Abdul Basit (Murattal)',      flag: '🇪🇬' },
  { id: 'ar.abdullahbasfar',     label: 'Abdullah Basfar',             flag: '🇸🇦' },
  { id: 'ar.abdurrahmaansudais', label: 'Abdul Rahman Al-Sudais',      flag: '🇸🇦' },
  { id: 'ar.shaatree',           label: 'Abu Bakr Ash-Shaatree',       flag: '🇸🇦' },
  { id: 'ar.ahmedajamy',         label: 'Ahmed Al-Ajamy',              flag: '🇸🇦' },
  { id: 'ar.hanirifai',          label: 'Hani Ar-Rifai',               flag: '🇸🇦' },
  { id: 'ar.husary',             label: 'Mahmoud Khalil Al-Husary',    flag: '🇪🇬' },
  { id: 'ar.husarymujawwad',     label: 'Al-Husary (Mujawwad)',        flag: '🇪🇬' },
  { id: 'ar.hudhaify',           label: 'Ali Al-Hudhaify',             flag: '🇸🇦' },
  { id: 'ar.ibrahimakhbar',      label: 'Ibrahim Al-Akhdar',           flag: '🇸🇦' },
  { id: 'ar.mahermuaiqly',       label: 'Maher Al-Muaiqly',            flag: '🇸🇦' },
  { id: 'ar.minshawi',           label: 'Mohamed Siddiq Al-Minshawi',  flag: '🇪🇬' },
  { id: 'ar.minshawimujawwad',   label: 'Al-Minshawi (Mujawwad)',      flag: '🇪🇬' },
  { id: 'ar.muhammadayyoub',     label: 'Muhammad Ayyoub',             flag: '🇸🇦' },
  { id: 'ar.muhammadjibreel',    label: 'Muhammad Jibreel',            flag: '🇪🇬' },
  { id: 'ar.saoodshuraym',       label: 'Saud Al-Shuraim',             flag: '🇸🇦' },
  { id: 'ar.parhizgar',          label: 'Shahriar Parhizgar',          flag: '🇮🇷' },
  { id: 'ar.aymanswoaid',        label: 'Ayman Sowaid',                flag: '🇸🇾' },
];

export const BITRATE_FALLBACK_ORDER = [128, 64, 192, 48, 40, 32];

export const TRANS_EDITIONS = {
  fr: 'fr.hamidullah',
  en: 'en.sahih',
  tr: 'tr.diyanet',
  ur: 'ur.jalandhry',
  de: 'de.aburida',
  es: 'es.asad',
  id: 'id.indonesian',
  ru: 'ru.kuliev',
};

export const TRANS_LABELS = {
  fr:'🇫🇷 FR', en:'🇬🇧 EN', tr:'🇹🇷 TR', ur:'🇵🇰 UR', de:'🇩🇪 DE', es:'🇪🇸 ES', id:'🇮🇩 ID', ru:'🇷🇺 RU'
};

export const SURAH_INFO = [
  { num:1,   nameEn:"Al-Fatiha",      nameAr:"الفاتحة",       revelation:"Mecquoise", ayats:7,   juz:1  },
  { num:2,   nameEn:"Al-Baqarah",     nameAr:"البقرة",        revelation:"Médinoise", ayats:286, juz:1  },
  { num:36,  nameEn:"Ya-Sin",         nameAr:"يس",            revelation:"Mecquoise", ayats:83,  juz:22 },
  { num:55,  nameEn:"Ar-Rahman",      nameAr:"الرحمن",        revelation:"Médinoise", ayats:78,  juz:27 },
  { num:67,  nameEn:"Al-Mulk",        nameAr:"الملك",         revelation:"Mecquoise", ayats:30,  juz:29 },
  { num:78,  nameEn:"An-Naba",        nameAr:"النبأ",         revelation:"Mecquoise", ayats:40,  juz:30 },
  { num:112, nameEn:"Al-Ikhlas",      nameAr:"الإخلاص",       revelation:"Mecquoise", ayats:4,   juz:30 },
  { num:113, nameEn:"Al-Falaq",       nameAr:"الفلق",         revelation:"Mecquoise", ayats:5,   juz:30 },
  { num:114, nameEn:"An-Nas",         nameAr:"الناس",         revelation:"Mecquoise", ayats:6,   juz:30 },
];

export const SUGGESTED_SEARCHES = [
  { label:"Lumière", query:"نور" },
  { label:"Pardon", query:"غفور" },
  { label:"Miséricorde", query:"رحمة" },
  { label:"Patience", query:"صبر" },
  { label:"Paradis", query:"جنات" },
  { label:"Cieux", query:"سماوات" },
];

export const SAJDA_AYATS = new Set([
  "7:206", "13:15", "16:50", "17:109", "19:58", "22:18", "22:77",
  "25:60", "27:26", "32:15", "38:24", "41:38", "53:62", "84:21", "96:19"
]);

export const PAGE_POSITION_LABELS = [
  "Début de page (1/3)",
  "Milieu de page (2/3)",
  "Fin de page (3/3)",
];

export const TAJWEED_RULES = [
  { id: 'qalqala', color: '#5bc8f5', label: 'Qalqala (قلقلة)',      labelAr: 'قلقلة', chars: ['ق','ط','ب','ج','د'] },
  { id: 'madd',    color: '#ff7eb3', label: 'Madd (مد)',            labelAr: 'مد',    chars: ['ا','و','ي','آ','ٰ'] },
  { id: 'izhar',   color: '#4caf81', label: 'Izhar (إظهار)',        labelAr: 'إظهار', chars: ['ء','ه','ع','غ','ح','خ'] },
  { id: 'idgham',  color: '#ffd166', label: 'Idgham (إدغام)',       labelAr: 'إدغام', chars: ['ي','ن','م','و','ل','ر'] },
  { id: 'ikhafa',  color: '#c878ff', label: 'Ikhfa (إخفاء)',        labelAr: 'إخفاء', chars: ['ت','ث','ج','د','ذ','ز','س','ش','ص','ض','ط','ظ','ف','ق','ك'] },
  { id: 'iqlab',   color: '#e05a5a', label: 'Iqlab (إقلاب)',        labelAr: 'إقلاب', chars: ['ب'] },
];

export const ARABIC_LETTERS = [
  { ar:'أ', name:'Alif',    trans:'a',  makhraj:'Gorge (basse)',   desc:'Son vocalique pur venant du fond de la gorge', forms:['أ','ـأ','ـأ','أ'] },
  { ar:'ب', name:'Ba',      trans:'b',  makhraj:'Lèvres',          desc:'Consonne occlusive bilabiale sonore',           forms:['ب','بـ','ـبـ','ـب'] },
  { ar:'ت', name:'Ta',      trans:'t',  makhraj:'Dents / Langue',  desc:'Consonne occlusive dentale sourde',            forms:['ت','تـ','ـتـ','ـت'] },
  { ar:'ث', name:'Tha',     trans:'th', makhraj:'Dents / Langue',  desc:'Interdentale sourde (comme "th" en anglais)',   forms:['ث','ثـ','ـثـ','ـث'] },
  { ar:'ج', name:'Jim',     trans:'j',  makhraj:'Palais',          desc:'Affriquée palatale sonore',                    forms:['ج','جـ','ـجـ','ـج'] },
  { ar:'ح', name:'Ha',      trans:'ḥ',  makhraj:'Gorge (médiane)', desc:'Fricative pharyngale sourde (aspirée forte)',  forms:['ح','حـ','ـحـ','ـح'] },
  { ar:'خ', name:'Kha',     trans:'kh', makhraj:'Gorge (haute)',   desc:'Fricative vélaire sourde (comme "ch" allemand)',forms:['خ','خـ','ـخـ','ـخ'] },
  { ar:'د', name:'Dal',     trans:'d',  makhraj:'Dents / Langue',  desc:'Occlusive dentale sonore',                     forms:['د','ـد','ـد','د'] },
  { ar:'ذ', name:'Dhal',    trans:'dh', makhraj:'Dents / Langue',  desc:'Interdentale sonore (comme "this" en anglais)', forms:['ذ','ـذ','ـذ','ذ'] },
  { ar:'ر', name:'Ra',      trans:'r',  makhraj:'Langue / Palais', desc:'Vibrante alvéolaire (roulée)',                 forms:['ر','ـر','ـر','ر'] },
  { ar:'ز', name:'Zay',     trans:'z',  makhraj:'Dents / Langue',  desc:'Fricative alvéolaire sonore',                  forms:['ز','ـز','ـز','ز'] },
  { ar:'س', name:'Sin',     trans:'s',  makhraj:'Dents / Langue',  desc:'Fricative alvéolaire sourde (siffiante)',     forms:['س','سـ','ـسـ','ـس'] },
  { ar:'ش', name:'Shin',    trans:'sh', makhraj:'Palais',          desc:'Fricative chuintante (comme "ch" en français)',forms:['ش','شـ','ـشـ','ـش'] },
  { ar:'ص', name:'Sad',     trans:'ṣ',  makhraj:'Dents / Langue',  desc:'Fricative alvéolaire emphatique (s lourd)',    forms:['ص','صـ','ـصـ','ـص'] },
  { ar:'ض', name:'Dad',     trans:'ḍ',  makhraj:'Langue / Dents',  desc:'Occlusive dentale emphatique (unique à l’arabe)',forms:['ض','ضـ','ـضـ','ـض'] },
  { ar:'ط', name:'Ta (e)',  trans:'ṭ',  makhraj:'Dents / Langue',  desc:'Occlusive dentale emphatique (t lourd)',       forms:['ط','طـ','ـطـ','ـط'] },
  { ar:'ظ', name:'Zha',     trans:'ẓ',  makhraj:'Dents / Langue',  desc:'Interdentale emphatique (dh lourd)',           forms:['ظ','ظـ','ـظـ','ـظ'] },
  { ar:'ع', name:'Ayn',     trans:'ʿ',  makhraj:'Gorge (médiane)', desc:'Fricative pharyngale sonore',                  forms:['ع','عـ','ـعـ','ـع'] },
  { ar:'غ', name:'Ghayn',   trans:'gh', makhraj:'Gorge (haute)',   desc:'Fricative vélaire sonore (comme "r" français)',forms:['غ','غـ','ـغـ','ـغ'] },
  { ar:'ف', name:'Fa',      trans:'f',  makhraj:'Lèvres / Dents',  desc:'Fricative labio-dentale sourde',               forms:['ف','فـ','ـفـ','ـف'] },
  { ar:'ق', name:'Qaf',     trans:'q',  makhraj:'Luette',          desc:'Occlusive uvulaire sourde (k profond)',        forms:['ق','قـ','ـقـ','ـق'] },
  { ar:'ك', name:'Kaf',     trans:'k',  makhraj:'Palais',          desc:'Occlusive vélaire sourde',                     forms:['ك','كـ','ـكـ','ـك'] },
  { ar:'ل', name:'Lam',     trans:'l',  makhraj:'Langue / Palais', desc:'Latérale alvéolaire',                          forms:['ل','لـ','ـلـ','ـل'] },
  { ar:'م', name:'Mim',     trans:'m',  makhraj:'Lèvres',          desc:'Nasale bilabiale',                             forms:['م','مـ','ـمـ','ـم'] },
  { ar:'ن', name:'Nun',     trans:'n',  makhraj:'Langue / Palais', desc:'Nasale alvéolaire',                            forms:['ن','نـ','ـنـ','ـن'] },
  { ar:'ه', name:'Ha (d)',  trans:'h',  makhraj:'Gorge (basse)',   desc:'Fricative glottale sourde (aspirée douce)',    forms:['ه','هـ','ـهـ','ـه'] },
  { ar:'و', name:'Waw',     trans:'w',  makhraj:'Lèvres',          desc:'Semi-voyelle labio-vélaire ou voyelle "ou"',   forms:['و','ـو','ـو','و'] },
  { ar:'ي', name:'Ya',      trans:'y',  makhraj:'Palais',          desc:'Semi-voyelle palatale ou voyelle "i"',         forms:['ي','يـ','ـيـ','ـي'] },
];

export const HARAKATS = [
  { symbol:'َ', name:'Fatha',   trans:'a',  desc:'Voyelle courte "a" (ex: بَ = ba)' },
  { symbol:'ُ', name:'Damma',   trans:'u',  desc:'Voyelle courte "ou" (ex: بُ = bou)' },
  { symbol:'ِ', name:'Kasra',   trans:'i',  desc:'Voyelle courte "i" (ex: بِ = bi)' },
  { symbol:'ً', name:'Tanwin Fath', trans:'an', desc:'Nasalisation "an" (ex: بً = ban)' },
  { symbol:'ٌ', name:'Tanwin Damm', trans:'un', desc:'Nasalisation "oun" (ex: بٌ = boun)' },
  { symbol:'ٍ', name:'Tanwin Kasr', trans:'in', desc:'Nasalisation "in" (ex: بٍ = bin)' },
  { symbol:'ّ', name:'Shadda',  trans:'°°', desc:'Doublement de la consonne (ex: بَّ = bba)' },
  { symbol:'ْ', name:'Sukun',   trans:'ø',  desc:'Absence de voyelle / arrêt (ex: بْ = b)' },
];

export const ARABIC_ROOTS = {
  "كتب": "écrire / livre",
  "رحم": "miséricorde",
  "علم": "savoir / science",
  "أمن": "foi / sécurité",
  "عبد": "adorer / serviteur",
  "خلق": "créer / création",
  "هدى": "guider / guidée",
  "ذكر": "rappeler / souvenir",
  "نصر": "secourir / victoire",
  "سمع": "entendre / ouïe",
  "بصر": "voir / vue",
  "قلب": "cœur / retourner",
  "أرض": "terre",
  "سما": "ciel / élever",
  "نور": "lumière",
  "حقق": "vérité / droit",
  "صبر": "patience",
  "شكر": "remercier / gratitude",
};

export const DATA_KEYS = [
  { key: "quran_learn_data",      label: "Données d'apprentissage" },
  { key: "quran_collections",     label: "Collections de versets" },
  { key: "quran_user_activity",   label: "Activité utilisateur" },
  { key: "quran_user_goals",      label: "Objectifs" },
  { key: "quran_reciter",         label: "Récitateur sélectionné" },
  { key: "quran_loop_by_surah",   label: "Boucles configurées" },
  { key: "quran_last_ayat",       label: "Dernières ayats lues" },
  { key: "quran_rev_mastery",     label: "Niveau de maîtrise" },
];
